import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./ui/components/Navbar1/Navbar";
const inter = Inter({ subsets: ["latin"] });
import { CustomApolloProvider } from "./client/apolloProvide";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
                <CustomApolloProvider>
                    {children}
                </CustomApolloProvider>
        </body>
    </html>
  );
}
