import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./ui/components/Navbar/Navbar";
const inter = Inter({ subsets: ["latin"] });
import { CustomApolloProvider } from "./client/apolloProvide";
import { getServerSession } from "next-auth";
import  SessionProvider  from "./utils/SessionProviders";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    const session = await getServerSession();
  return (
    <html lang="en">
            <body className={inter.className}>
                <CustomApolloProvider>
                <SessionProvider session={session}>
                        <Navbar/>
                        {children}
                </SessionProvider>
                </CustomApolloProvider>
            </body>
    </html>
  );
}
